name: test-workflow
on:
    workflow_dispatch:
        inputs:
            target-environment:
                description: 'Environment to deploy to'
                type: environment
                required: true

jobs:
    playground:
        runs-on: ubuntu-latest
        env:
            NODE_VERSION: '20'
        environment: ${{ github.event.inputs['target-environment'] }}
        steps:
            - name: Playground
              id: playground
              run: |
                  echo "TEST-environment: ${{ github.event.inputs['target-environment'] }}"
                  echo "TEST-SECRET_A: ${{ secrets.SECRET_A }}"
                  echo "TEST-SECRET_B: ${{ secrets.SECRET_B }}"
                  echo "TEST-ENV_A: ${{ vars.VARIABLE_A }}"
                  echo "TEST-ENV_B: ${{ vars.VARIABLE_B }}"
                  echo "------------------------------------------"
                  echo "TEST-secrets: ${{ secrets }}"
                  echo "TEST-vars: ${{ vars }}"

