name: test-workflow
on:
  workflow_dispatch:
    inputs:
      target-environment:
        description: "Environment to deploy to"
        type: environment
        required: true

jobs:
  playground:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "20"

    environment: ${{ github.event.inputs['target-environment'] }}
    steps:
      - uses: actions/checkout@v3

      - name: Generate .env file
        uses: ./.github/actions/generate-env-file
        env:
          BUILD_VERSION: ${{ github.sha }}
          APP_ENV: ${{ github.event.inputs['target-environment'] }}
        with:
          env_vars: ${{ toJSON(vars) }}
          template: ".env.template"
          output: ".env"

      - name: Debug
        id: debug
        run: |
          cat .env
