name: test-workflow
on:
  workflow_dispatch:
    inputs:
      target-environment:
        description: "Environment to deploy to"
        type: environment
        required: true

jobs:
  playground:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "20"

    environment: ${{ github.event.inputs['target-environment'] }}
    steps:
      - uses: actions/checkout@v3

      - name: Playground
        id: playground
        env:
          ALL_VARS: ${{ toJSON(vars) }}
        run: |
          echo "ALL_VARS: $ALL_VARS"
          # envsubst < .env.template > .env
          # cat .env

