name: test-workflow
on:
  workflow_dispatch:
    inputs:
      target-environment:
        description: "Environment to deploy to"
        type: environment
        required: true

jobs:
  playground:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: "20"

    environment: ${{ github.event.inputs['target-environment'] }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup dynamic variables
        id: dynamic-vars
        run: |
          # Create JSON using heredoc with dynamic values
          json=$(cat <<EOF
          {
            "BUILD_VERSION": "${{ github.sha }}",
            "APP_ENV": "${{ inputs.environment || github.ref_name == 'main' && 'production' || 'staging' }}"
          }
          EOF
          )
          
          # Store in outputs using multiline syntax
          echo "json<<EOF" >> $GITHUB_OUTPUT
          echo "$json" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Generate .env file
        uses: ./.github/actions/generate-env-file
        with:
          env_vars: ${{ toJSON(vars) }}
          dynamic_vars: ${{ steps.dynamic-vars.outputs.json }}
          template: ".env.template"
          output: ".env"

      - name: Debug
        id: debug
        run: |
          cat .env
